# General parameters
VERSION   = "0.1"
BLM       = as.character(BLM)
PROP      = "0"
RANDSEED  = "-1"
BESTSCORE = "0"
NUMREPS   = as.character(nb.runs)

# Annealing parameters
NUMITNS   = "1000000"
STARTTEMP = "-1"
COOLFAC   = "6"
NUMTEMP   = "100000"

# Cost Threshold
COSTTHRESH = "0"
THRESHPEN1 = "0"
THRESHPEN2 = "0"

# Input Files
INPUTDIR   = "input"
SPECNAME   = "spec.dat"
PUNAME     = "pu.dat"
PUVSPRNAME = "puvspr.dat"
BOUNDNAME  = "bound.dat"

# Save Files
SCENNAME            = scenario
SAVERUN             = "3"
SAVEBEST            = "3"
SAVESUMMARY         = "3"
SAVESCEN            = "2"
SAVETARGMET         = "3"
SAVESUMSOLN         = "3"
SAVESOLUTIONSMATRIX = "3"
SAVELOG             = "2"
OUTPUTDIR           = "output"

# Program control.
RUNMODE   = "1"
CLUMPTYPE = "0"
VERBOSITY = "3"

# input.dat generation
writeLines(sprintf("This file generated by marxan.net\nemailto: m.watts@uq.edu.au\n\n
General Parameters\nVERSION %s\nBLM %s\nPROP %s\nRANDSEED %s\nBESTSCORE %s\nNUMREPS %s\n\n
Annealing Parameters\nNUMITNS %s\nSTARTTEMP %s\nCOOLFAC %s\nNUMTEMP %s\n\n
Cost Threshold\nCOSTTHRESH %s\nTHRESHPEN1 %s\nTHRESHPEN2 %s\n\n
Input Files\nINPUTDIR %s\nSPECNAME %s\nPUNAME %s\nPUVSPRNAME %s\nBOUNDNAME %s\n\n
Save Files\nSCENNAME %s\nSAVERUN %s\nSAVEBEST %s\nSAVESUMMARY %s\nSAVESCEN %s\nSAVETARGMET %s\nSAVESUMSOLN %s\nSAVESOLUTIONSMATRIX %s\nSAVELOG %s\nOUTPUTDIR %s\n\n
Program control.\nRUNMODE %s\nCLUMPTYPE %s\nVERBOSITY %s\n\n",
VERSION,BLM,PROP,RANDSEED,BESTSCORE,NUMREPS,
NUMITNS,STARTTEMP,COOLFAC,NUMTEMP,
COSTTHRESH,THRESHPEN1,THRESHPEN2,
INPUTDIR,SPECNAME,PUNAME,PUVSPRNAME,BOUNDNAME,
SCENNAME,SAVERUN ,SAVEBEST,SAVESUMMARY,SAVESCEN,SAVETARGMET,SAVESUMSOLN ,SAVESOLUTIONSMATRIX,SAVELOG,OUTPUTDIR,
RUNMODE,CLUMPTYPE,VERBOSITY),paste0(root.dir,"/3_results/",folder,"/input.dat"))




